/**
 * genStickerFree - 무료 사용자용 스티커 생성 함수
 *
 * 2단계 폴백 시스템 사용:
 * 1차: Pixazo ($0.0012/이미지)
 * 2차: OpenAI ($0.005/이미지)
 *
 * 기존 genSticker와 동일한 인터페이스 유지
 */

import * as functions from "firebase-functions";
import * as admin from "firebase-admin";
import sharp from "sharp";
import {
  generateImageWithFallback,
  FallbackConfig,
  calculateCost,
  getProviderDisplayName,
} from "./utils/fallbackManager";
import {recordApiCall} from "./utils/monitoring";

// genSticker와 동일한 인터페이스
interface GenStickerFreeRequest {
  petId: string;
  breed?: string;
  color?: string;
  accessory?: "none" | "bandana" | "glasses" | "bowtie" | "hat" | "collar";
  style?: "sticker-flat" | "sticker-3d" | "realistic";
  size?: number;
  bg?: "transparent" | "white" | "gradient";
  seed?: number;
  force?: boolean;
}

// 무료 사용자 일일 할당량
const FREE_USER_DAILY_QUOTA = 10;

export const genStickerFree = functions
  .region("us-central1")
  .https.onCall(async (data: GenStickerFreeRequest, context) => {
    console.log("🎨 [genStickerFree] Called");

    // =====================
    // 1. App Check 검증
    // =====================
    if (!context.app) {
      throw new functions.https.HttpsError(
        "failed-precondition",
        "App Check required"
      );
    }

    // =====================
    // 2. 인증 확인 (필수)
    // =====================
    if (!context.auth) {
      throw new functions.https.HttpsError(
        "unauthenticated",
        "Authentication required"
      );
    }
    const uid = context.auth.uid;
    console.log(`👤 [genStickerFree] User: ${uid}`);

    // =====================
    // 3. 입력 검증
    // =====================
    const {
      petId,
      breed = "Shiba Inu",
      color = "orange",
      accessory = "none",
      style = "sticker-flat",
      size = 512,
      bg = "transparent",
      seed,
    } = data;

    console.log(`📝 [genStickerFree] petId=${petId}`);

    if (!petId || size < 256 || size > 1024) {
      console.error("❌ [genStickerFree] Invalid parameters");
      throw new functions.https.HttpsError("invalid-argument", "Invalid parameters");
    }

    // =====================
    // 4. 레이트 리밋 체크
    // =====================
    const rateLimitOk = await checkAndReserveSlot(uid, FREE_USER_DAILY_QUOTA);
    if (!rateLimitOk) {
      console.error(`❌ [genStickerFree] Rate limit exceeded for user ${uid}`);
      throw new functions.https.HttpsError(
        "resource-exhausted",
        `Daily limit reached (${FREE_USER_DAILY_QUOTA} images/day for free users)`
      );
    }

    // =====================
    // 4. API 키 로드
    // =====================
    const config = functions.config();
    const pixazoApiKey = config.pixazo?.api_key;
    const openaiApiKey = config.openai?.api_key;

    if (!pixazoApiKey) {
      console.error("❌ [genStickerFree] Pixazo API key not configured");
      throw new functions.https.HttpsError("internal", "Pixazo API key not configured");
    }

    if (!openaiApiKey) {
      console.error("❌ [genStickerFree] OpenAI API key not configured");
      throw new functions.https.HttpsError("internal", "OpenAI API key not configured");
    }

    console.log("🔑 [genStickerFree] API keys configured");

    // =====================
    // 5. 프롬프트 생성 (genSticker와 동일한 로직)
    // =====================
    const prompt = generatePrompt(breed, color, accessory, style, bg);
    console.log(`📝 [genStickerFree] Prompt: ${prompt}`);

    // =====================
    // 6. 폴백 시스템으로 이미지 생성
    // =====================
    const fallbackConfig: FallbackConfig = {
      pixazoApiKey,
      openaiApiKey,
    };

    const startTime = Date.now();
    const result = await generateImageWithFallback(fallbackConfig, {
      prompt,
      size: 1024, // 항상 1024로 생성 후 리사이즈
      seed,
    });
    const totalDuration = Date.now() - startTime;

    if (!result.success || !result.imageBuffer) {
      console.error(`❌ [genStickerFree] All providers failed after ${totalDuration}ms`);
      console.error(`❌ [genStickerFree] Attempts: ${JSON.stringify(result.attempts)}`);

      // 실패 모니터링 기록
      await recordApiCall({
        provider: result.provider,
        success: false,
        durationMs: totalDuration,
        fallbackUsed: result.attempts.length > 1,
        fallbackReason: result.attempts[0]?.error,
        error: result.error || "All providers failed",
        attempts: result.attempts,
      });

      throw new functions.https.HttpsError("internal", "Image generation failed with all providers");
    }

    // 성공 모니터링 기록
    const fallbackUsed = result.attempts.length > 1 && result.provider !== "pixazo";
    await recordApiCall({
      provider: result.provider,
      success: true,
      durationMs: totalDuration,
      fallbackUsed,
      fallbackReason: fallbackUsed ? result.attempts[0]?.error : undefined,
      attempts: result.attempts,
    });

    console.log(`✅ [genStickerFree] Image generated by ${result.provider} in ${totalDuration}ms`);

    // =====================
    // 7. 이미지 처리 (WebP 변환)
    // =====================
    console.log("🔄 [genStickerFree] Converting to WebP...");
    const webpImage = await convertToWebP(result.imageBuffer, size);
    const base64Image = webpImage.toString("base64");
    console.log(`✅ [genStickerFree] WebP conversion complete, size: ${base64Image.length} chars`);

    // =====================
    // 8. 사용량 기록
    // =====================
    await recordProviderInfo(uid, result.provider);
    console.log(`📊 [genStickerFree] Usage recorded for user ${uid}`);

    // =====================
    // 9. 응답 반환 (genSticker와 동일한 형식 + 추가 정보)
    // =====================
    const response = {
      success: true,
      data: {
        image_base64: base64Image,
        mime: "image/webp",
        seed: seed || Date.now(),
        cached: false,
        size: {width: size, height: size},
        metadata: {breed, color, accessory, style},
        // 무료 사용자용 추가 정보
        provider: result.provider,
        providerName: getProviderDisplayName(result.provider),
        estimatedCost: calculateCost(result.provider),
        attempts: result.attempts,
        totalDurationMs: totalDuration,
      },
    };

    console.log(`🎉 [genStickerFree] Returning success response (provider: ${result.provider})`);
    return response;
  });

// =====================
// 유틸리티 함수들
// =====================

/**
 * 프롬프트 생성 (genSticker와 동일한 로직)
 */
function generatePrompt(
  breed: string,
  color: string,
  accessory: string,
  style: string,
  bg: string
): string {
  let prompt = `${breed} dog, ${color} coat, cute sticker, front view, simple shading, 2D flat`;

  if (accessory !== "none") {
    const accessoryMap: Record<string, string> = {
      bandana: "red bandana accessory",
      glasses: "sunglasses accessory",
      bowtie: "bow tie accessory",
      hat: "top hat accessory",
      collar: "decorative collar",
    };
    prompt += `, ${accessoryMap[accessory]}`;
  }

  prompt += `, ${bg} background`;

  return prompt;
}

/**
 * WebP 변환
 */
async function convertToWebP(imageBuffer: Buffer, size: number): Promise<Buffer> {
  return await sharp(imageBuffer)
    .resize(size, size)
    .webp({quality: 90})
    .toBuffer();
}

/**
 * 레이트 리밋 체크 + 슬롯 예약 (원자적)
 *
 * Firestore Transaction으로 check + increment 원자적 수행.
 * TOCTOU race condition 방지 (H-2).
 * Firestore 오류 시 fail-closed (H-1).
 */
async function checkAndReserveSlot(
  uid: string, dailyQuota: number
): Promise<boolean> {
  const db = admin.firestore();
  const today = new Date().toISOString().split("T")[0];
  const usageRef = db.collection("freeImageUsage").doc(uid);

  try {
    return await db.runTransaction(async (tx) => {
      const usageDoc = await tx.get(usageRef);
      const usage = usageDoc.data();
      const currentCount =
        (usage && usage.date === today) ?
          (usage.count || 0) : 0;

      if (currentCount >= dailyQuota) {
        return false;
      }

      // 원자적으로 카운터 증가
      const now = Date.now();
      if (!usageDoc.exists || usage?.date !== today) {
        tx.set(usageRef, {
          date: today,
          count: 1,
          timestamps: [now],
        });
      } else {
        tx.update(usageRef, {
          count: currentCount + 1,
          timestamps:
            admin.firestore.FieldValue.arrayUnion(now),
        });
      }

      return true;
    });
  } catch (error) {
    console.error(
      "❌ [genStickerFree] Rate limit check failed:", error
    );
    // Firestore 오류 시 차단 (fail-closed)
    return false;
  }
}

/**
 * Provider 정보 기록 (모니터링용)
 *
 * 카운터는 checkAndReserveSlot에서 이미 원자적으로 증가됨.
 * 여기서는 provider 메타데이터만 업데이트.
 */
async function recordProviderInfo(
  uid: string, provider: string
): Promise<void> {
  const db = admin.firestore();
  const usageRef = db.collection("freeImageUsage").doc(uid);

  try {
    await usageRef.update({
      providers:
        admin.firestore.FieldValue.arrayUnion(provider),
      lastProvider: provider,
    });
  } catch (error) {
    console.error(
      "❌ [genStickerFree] Error recording provider:", error
    );
  }
}
