// File generated by FlutterFire CLI (manually configured)
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.macOS:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZrFZSPt-4dyKnj_XdJ8otOpzT3z1s4_U',
    appId: '1:701057110809:web:5e7fc1686b8d49ed9a2b88',
    messagingSenderId: '701057110809',
    projectId: 'walkwalkddog',
    authDomain: 'walkwalkddog.firebaseapp.com',
    storageBucket: 'walkwalkddog.firebasestorage.app',
    measurementId: 'G-ZNKF44B03T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDorGbyRC7ljIM_Y4DCZOOB9MmX2AreXZg',
    appId: '1:701057110809:android:61d3ecd893ab595d9a2b88',
    messagingSenderId: '701057110809',
    projectId: 'walkwalkddog',
    storageBucket: 'walkwalkddog.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClLFoC3Zcc7AmfNCXpGsxs6FiAottlnwM',
    appId: '1:701057110809:ios:ece40fa68f5eac209a2b88',
    messagingSenderId: '701057110809',
    projectId: 'walkwalkddog',
    storageBucket: 'walkwalkddog.firebasestorage.app',
    iosBundleId: 'com.walkdog.walkDog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZrFZSPt-4dyKnj_XdJ8otOpzT3z1s4_U',
    appId: '1:701057110809:windows:walkwalkddog',
    messagingSenderId: '701057110809',
    projectId: 'walkwalkddog',
    authDomain: 'walkwalkddog.firebaseapp.com',
    storageBucket: 'walkwalkddog.firebasestorage.app',
  );
}