// File generated by FlutterFire CLI (manually configured)
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX-fH8S1VdIJ7GnrEC2KC0k7kjwUnc5CY',
    appId: '1:701057110809:web:walkwalkddog',
    messagingSenderId: '701057110809',
    projectId: 'walkwalkddog',
    authDomain: 'walkwalkddog.firebaseapp.com',
    storageBucket: 'walkwalkddog.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX-fH8S1VdIJ7GnrEC2KC0k7kjwUnc5CY',
    appId: '1:701057110809:android:61d3ecd893ab595d9a2b88',
    messagingSenderId: '701057110809',
    projectId: 'walkwalkddog',
    storageBucket: 'walkwalkddog.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClctG7hqrRYUvlbvsZcluGxf9nNP2CxOY',
    appId: '1:701057110809:ios:b021e3f705864e189a2b88',
    messagingSenderId: '701057110809',
    projectId: 'walkwalkddog',
    storageBucket: 'walkwalkddog.firebasestorage.app',
    iosBundleId: 'com.walkdogbin.walkDog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClctG7hqrRYUvlbvsZcluGxf9nNP2CxOY',
    appId: '1:701057110809:macos:walkwalkddog',
    messagingSenderId: '701057110809',
    projectId: 'walkwalkddog',
    storageBucket: 'walkwalkddog.firebasestorage.app',
    iosBundleId: 'com.walkdog.walkDog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX-fH8S1VdIJ7GnrEC2KC0k7kjwUnc5CY',
    appId: '1:701057110809:windows:walkwalkddog',
    messagingSenderId: '701057110809',
    projectId: 'walkwalkddog',
    authDomain: 'walkwalkddog.firebaseapp.com',
    storageBucket: 'walkwalkddog.firebasestorage.app',
  );
}
